services:
  headless_chrome:
    ports:
      - '5000:3000'

  www:
    container_name: www
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - '80:80'
      - '443:443'
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  backend:
    networks:
      - caddy
    labels:
      caddy: ${BASE_DOMAIN}
      caddy.0_redir: "/pb /pb/_/"
      caddy.1_redir: "/pb/_ /pb/_/"
      caddy.2_handle_path: /pb/*
      caddy.2_handle_path.0_rewrite: "/pb/* /{path}"
      caddy.2_handle_path.1_reverse_proxy: "{{upstreams 8090}}"

    restart: always

  frontend:
    networks:
      - caddy 
    labels:
      caddy: ${BASE_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: always

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}